import { Component, OnInit } from '@angular/core';
import { ButtonFilterComponent } from 'src/app/shared/button-filter/button-filter.component';
import { SharedModule } from 'src/app/shared/shared.module';
import { IonActionSheet, IonButton } from '@ionic/angular/standalone';
import { FormGroup } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-scoring-five-s',
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss'],
  standalone: true,
  imports: [SharedModule, ButtonFilterComponent, IonActionSheet, IonButton],
})
export class ListComponent implements OnInit {
  filterData: any;
  searchTime: any = ''
  searchNguoiCham: any = ''
  searchStore: any = ''
  selectValue = '1';
  filterForm!: FormGroup;

  constructor(
    private router: Router
  ) { }

  initData: any[] = [
    {
      status: true,
      data: {
        kiKhaoSat: {
          id: '2214b81a-5d0c-4013-9110-de79d667fb95',
          code: 'T042025',
          name: 'T042025',
          des: '-                                                 ',
          startDate: '2025-04-29T18:58:35.44',
          surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
          endDate: '2025-05-30T18:58:35.44',
          isDeleted: false,
          deleteDate: null,
          deleteBy: null,
          isActive: true,
          createBy: 'admin',
          updateBy: null,
          createDate: '2025-05-26T14:12:26.89',
          updateDate: null,
        },
        lstInputStore: [
          {
            id: '281046',
            phoneNumber: '0383858310',
            name: 'PETROLIMEX-CỬA HÀNG 08',
            cuaHangTruong: 'Nguyễn Thị Thu Hương',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281046',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: ['phuongtt', 'thind'],
            lstInChamDiem: [
              {
                id: '1dfa0fe4-c050-4eff-bd2c-c264b1ba856b',
                inStoreId: '281046',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'phuongtt',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
              {
                id: 'cca2469a-30fc-4d28-8130-e87ad2a2a133',
                inStoreId: '281046',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'thind',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
            ],
          },
          {
            id: '281059',
            phoneNumber: '0383961368',
            name: 'PETROLIMEX-CỬA HÀNG 173',
            cuaHangTruong: 'Hoàng Thị Tuyết',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281059',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: ['kienht'],
            lstInChamDiem: [
              {
                id: 'bba112b6-d753-4363-8ba7-2276e13aae4b',
                inStoreId: '281059',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'kienht',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
            ],
          },
          {
            id: '281013',
            phoneNumber: '0388662039',
            name: 'PETROLIMEX-CỬA HÀNG 131',
            cuaHangTruong: 'Hồ Xuân Hưng',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281013',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: ['kienht', 'admin'],
            lstInChamDiem: [
              {
                id: 'b0e28b25-b6ec-44e6-bc99-9fdc74dab110',
                inStoreId: '281013',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'kienht',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
              {
                id: 'da859b43-e2a1-41c4-9701-51288584a504',
                inStoreId: '281013',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'admin',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
            ],
          },
          {
            id: '281025',
            phoneNumber: '0383944385',
            name: 'PETROLIMEX-CỬA HÀNG 22',
            cuaHangTruong: 'Võ Văn Lưc',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281025',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: ['admin', 'thind', 'phuongtt'],
            lstInChamDiem: [
              {
                id: '179bb845-00f9-4eca-bf2d-6f76120e56d5',
                inStoreId: '281025',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'admin',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
              {
                id: 'cea09233-b390-4a0c-8a0f-58452952dbf9',
                inStoreId: '281025',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'thind',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
              {
                id: 'f9a6cf1a-c6ba-44e4-823e-6e1c547b33de',
                inStoreId: '281025',
                kiKhaoSatId: '2214b81a-5d0c-4013-9110-de79d667fb95',
                userName: 'phuongtt',
                isDeleted: false,
                deleteDate: null,
                deleteBy: null,
                isActive: true,
                createBy: 'admin',
                updateBy: null,
                createDate: '2025-05-26T14:12:26.89',
                updateDate: null,
              },
            ],
          },
          {
            id: '281027',
            phoneNumber: '0383928433',
            name: 'PETROLIMEX-CỬA HÀNG 50',
            cuaHangTruong: 'Nguyễn Văn Phương',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281027',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281033',
            phoneNumber: '0383863647',
            name: 'PETROLIMEX-CỬA HÀNG 61',
            cuaHangTruong: 'Hồ Trọng Giang',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281033',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281048',
            phoneNumber: '0383983062',
            name: 'PETROLIMEX-CỬA HÀNG 177',
            cuaHangTruong: 'Trần Thị Hải Yến',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281048',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281002',
            phoneNumber: '0383852398',
            name: 'PETROLIMEX-CỬA HÀNG 03',
            cuaHangTruong: 'Doãn Thành Vinh',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281002',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281075',
            phoneNumber: '0383626299',
            name: 'PETROLIMEX-CỬA HÀNG 170',
            cuaHangTruong: 'Trần Phạm Thanh',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281075',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281035',
            phoneNumber: '0388666610',
            name: 'PETROLIMEX-CỬA HÀNG 41',
            cuaHangTruong: 'Hoàng Minh Hà',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281035',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281036',
            phoneNumber: '0383655236',
            name: 'PETROLIMEX-CỬA HÀNG 71',
            cuaHangTruong: 'Trần Đại Đường',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281036',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281031',
            phoneNumber: '0383675112',
            name: 'PETROLIMEX-CỬA HÀNG 108',
            cuaHangTruong: 'Nguyễn Văn Trọng',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281031',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281061',
            phoneNumber: '0383611995',
            name: 'PETROLIMEX-CỬA HÀNG 26',
            cuaHangTruong: 'Lê Quang Vinh',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281061',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281005',
            phoneNumber: '0383851609',
            name: 'PETROLIMEX-CỬA HÀNG 04',
            cuaHangTruong: 'Trương Thị Nguyệt',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281005',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281057',
            phoneNumber: '0383785170',
            name: 'PETROLIMEX-CỬA HÀNG 43',
            cuaHangTruong: 'Lưu Xuân Phan',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281057',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281012',
            phoneNumber: '0383596096',
            name: 'PETROLIMEX-CỬA HÀNG 11',
            cuaHangTruong: 'Đinh Chí Dũng',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281012',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281017',
            phoneNumber: '0383771864',
            name: 'PETROLIMEX-CỬA HÀNG 113',
            cuaHangTruong: 'Trương Hải',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281017',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281099',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 16',
            cuaHangTruong: 'Trần Minh Thanh',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281099',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281019',
            phoneNumber: '0383812819',
            name: 'PETROLIMEX-CỬA HÀNG 172',
            cuaHangTruong: 'Hoàng Thị Hường',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281019',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281001',
            phoneNumber: '0383596052',
            name: 'PETROLIMEX-CỬA HÀNG 01',
            cuaHangTruong: 'thind',
            nguoiPhuTrach: 'thind',
            viDo: '2',
            kinhDo: '1',
            trangThaiCuaHang: true,
            storeId: '281001',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281095',
            phoneNumber: '0869589055',
            name: 'PETROLIMEX-CỬA HÀNG 55',
            cuaHangTruong: 'Nguyễn Sĩ Sinh',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281095',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281040',
            phoneNumber: '0383594733',
            name: 'PETROLIMEX-CỬA HÀNG 06',
            cuaHangTruong: 'Nguyễn Tuấn Long',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281040',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281053',
            phoneNumber: '0383771079',
            name: 'PETROLIMEX-CỬA HÀNG 112',
            cuaHangTruong: 'Hoàng Văn Cường',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281053',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281052',
            phoneNumber: '0383557899',
            name: 'PETROLIMEX-CỬA HÀNG 09',
            cuaHangTruong: 'Phạm Tiến Dũng',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281052',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281024',
            phoneNumber: '0383719323',
            name: 'PETROLIMEX-CỬA HÀNG 152',
            cuaHangTruong: 'Khiếu Mộng Thành Lâm',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281024',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281094',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 28',
            cuaHangTruong: 'Trần Trung Thông',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281094',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281010',
            phoneNumber: '0383949020',
            name: 'PETROLIMEX-CỬA HÀNG 21',
            cuaHangTruong: 'Phùng Đức Thành',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281010',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281030',
            phoneNumber: '0383651471',
            name: 'PETROLIMEX-CỬA HÀNG 72',
            cuaHangTruong: 'Đặng Nam Giang',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281030',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281056',
            phoneNumber: '0383901899',
            name: 'PETROLIMEX-CỬA HÀNG 174',
            cuaHangTruong: 'Tạ Quang Đức',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281056',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281020',
            phoneNumber: '0383888623',
            name: 'PETROLIMEX-CỬA HÀNG 175',
            cuaHangTruong: 'Trần Xuân Lai',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281020',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281008',
            phoneNumber: '0383858310',
            name: 'PETROLIMEX-CỬA HÀNG 100',
            cuaHangTruong: 'Nguyễn Duy Tú',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281008',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281050',
            phoneNumber: '0383670689',
            name: 'PETROLIMEX-CỬA HÀNG 110',
            cuaHangTruong: 'Nguyễn Trung Thành',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281050',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281015',
            phoneNumber: '0383796049',
            name: 'PETROLIMEX-CỬA HÀNG 24',
            cuaHangTruong: 'Phan Viết Sơn',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281015',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281034',
            phoneNumber: '0383676311',
            name: 'PETROLIMEX-CỬA HÀNG 109',
            cuaHangTruong: 'Nguyễn Văn Dương',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281034',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281003',
            phoneNumber: '0383842076',
            name: 'PETROLIMEX-CỬA HÀNG 02',
            cuaHangTruong: 'Nguyễn Thị Vinh',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281003',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281038',
            phoneNumber: '0383646125',
            name: 'PETROLIMEX-CỬA HÀNG 114',
            cuaHangTruong: 'Nguyễn Hải Vân',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281038',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281043',
            phoneNumber: '0383628350',
            name: 'PETROLIMEX-CỬA HÀNG 60',
            cuaHangTruong: 'Nguyễn Sỹ Thanh',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281043',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281032',
            phoneNumber: '0383862060',
            name: 'PETROLIMEX-CỬA HÀNG 105',
            cuaHangTruong: 'Nguyễn Sỹ Thanh',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281032',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281058',
            phoneNumber: '0383650924',
            name: 'PETROLIMEX-CỬA HÀNG 171',
            cuaHangTruong: 'Hồ Xuân Phú',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281058',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281074',
            phoneNumber: '0383693693',
            name: 'PETROLIMEX-CỬA HÀNG 154',
            cuaHangTruong: 'Phan Đình Lan',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281074',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281062',
            phoneNumber: '0383602358',
            name: 'PETROLIMEX-CỬA HÀNG 104',
            cuaHangTruong: 'Nguyễn Đức Đông',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281062',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281096',
            phoneNumber: '0869589073',
            name: 'PETROLIMEX-CỬA HÀNG 73',
            cuaHangTruong: 'Đặng Nam Giang',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281096',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281076',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 137',
            cuaHangTruong: 'Nguyễn Kim Mạnh Thắng',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281076',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281023',
            phoneNumber: '0383927889',
            name: 'PETROLIMEX-CỬA HÀNG 136',
            cuaHangTruong: 'Lê Thanh Trung',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281023',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281022',
            phoneNumber: '0383888159',
            name: 'PETROLIMEX-CỬA HÀNG 176',
            cuaHangTruong: 'Trịnh Thanh Tùng',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281022',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281055',
            phoneNumber: '0383970688',
            name: 'PETROLIMEX-CỬA HÀNG 53',
            cuaHangTruong: 'Phạm Văn Khánh',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281055',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281029',
            phoneNumber: '0383664273',
            name: 'PETROLIMEX-CỬA HÀNG 117',
            cuaHangTruong: 'Trần Hải Dương',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281029',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281045',
            phoneNumber: '0383716552',
            name: 'PETROLIMEX-CỬA HÀNG 153',
            cuaHangTruong: 'Nguyễn Phi Long',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281045',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281051',
            phoneNumber: '0383564318',
            name: 'PETROLIMEX-CỬA HÀNG 12',
            cuaHangTruong: 'Lê Văn Tuyến',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281051',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281064',
            phoneNumber: '038046846',
            name: 'CH PP Gas Vinh - Trung Tâm KDTH',
            cuaHangTruong: 'Nguyễn Đình Sơn CH PP',
            nguoiPhuTrach: '',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281064',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281101',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 17',
            cuaHangTruong: 'Lê Thị Lệ Thủy',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281101',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281054',
            phoneNumber: '0383882898',
            name: 'PETROLIMEX-CỬA HÀNG 52',
            cuaHangTruong: 'Tăng Văn Tuấn',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281054',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281044',
            phoneNumber: '0383825025',
            name: 'PETROLIMEX-CỬA HÀNG 132',
            cuaHangTruong: 'Trần Gia Hà',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281044',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281016',
            phoneNumber: '0383862322',
            name: 'PETROLIMEX-CỬA HÀNG 106',
            cuaHangTruong: 'Biện Thanh Tường',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281016',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281102',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 77',
            cuaHangTruong: 'Đoàn Hiệp',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281102',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281097',
            phoneNumber: '0869589075',
            name: 'PETROLIMEX-CỬA HÀNG 75',
            cuaHangTruong: 'Nguyễn Công Dương',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281097',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281072',
            phoneNumber: '0383774707',
            name: 'PETROLIMEX-CỬA HÀNG 70',
            cuaHangTruong: 'Đậu Đức Hoàng',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281072',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281011',
            phoneNumber: '0383791204',
            name: 'PETROLIMEX-CỬA HÀNG 103',
            cuaHangTruong: 'Nguyễn Thành Vinh',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281011',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281039',
            phoneNumber: '0383730181',
            name: 'PETROLIMEX-CỬA HÀNG 156',
            cuaHangTruong: 'Phan Sỹ Đoàn',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281039',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281077',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 51',
            cuaHangTruong: 'Bùi Hữu Giang',
            nguoiPhuTrach: 'Tạ Quang Hòa',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281077',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281004',
            phoneNumber: '0383851301',
            name: 'PETROLIMEX-CỬA HÀNG 05',
            cuaHangTruong: 'Võ Duy Giảng',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281004',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281007',
            phoneNumber: '0383842072',
            name: 'PETROLIMEX-CỬA HÀNG 07',
            cuaHangTruong: 'Trần Thị Ngọc',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281007',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281009',
            phoneNumber: '0383829651',
            name: 'PETROLIMEX-CỬA HÀNG 20',
            cuaHangTruong: 'Nguyễn Thế Anh',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281009',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281028',
            phoneNumber: '0383822377',
            name: 'PETROLIMEX-CỬA HÀNG 134',
            cuaHangTruong: 'Nguyễn Sỹ Tân',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281028',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281037',
            phoneNumber: '0383866064',
            name: 'PETROLIMEX-CỬA HÀNG 74',
            cuaHangTruong: 'Nguyễn Công Dương',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281037',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281018',
            phoneNumber: '0383866112',
            name: 'PETROLIMEX-CỬA HÀNG 115',
            cuaHangTruong: 'Trần Quang Cảnh',
            nguoiPhuTrach: 'Trần Hải Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281018',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281042',
            phoneNumber: '0383671002',
            name: 'PETROLIMEX-CỬA HÀNG 111',
            cuaHangTruong: 'Tạ Quang Nam',
            nguoiPhuTrach: 'Phan Bá Hậu',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281042',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281049',
            phoneNumber: '0383538919',
            name: 'PETROLIMEX-CỬA HÀNG 15',
            cuaHangTruong: 'Nguyễn Thị Thịnh',
            nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281049',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281047',
            phoneNumber: '0383819112',
            name: 'PETROLIMEX-CỬA HÀNG 90',
            cuaHangTruong: 'Vũ Quốc Hiếu',
            nguoiPhuTrach: 'Hồ Thanh Tùng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281047',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281103',
            phoneNumber: '',
            name: 'PETROLIMEX-CỬA HÀNG 29',
            cuaHangTruong: 'Nguyễn Hữu Vinh',
            nguoiPhuTrach: 'Trần Bảo Toàn',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281103',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
          {
            id: '281041',
            phoneNumber: '0383762877',
            name: 'PETROLIMEX-CỬA HÀNG 130',
            cuaHangTruong: 'Nguyễn Hữu Cường',
            nguoiPhuTrach: 'Võ Thành Đồng',
            viDo: null,
            kinhDo: null,
            trangThaiCuaHang: true,
            storeId: '281041',
            surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
            lstChamDiem: [],
            lstInChamDiem: [],
          },
        ],
        lstInputWareHouse: [],
        kyCopyId: null,
      },
    },
  ];

  data: any[] = [...this.initData];
  ngOnInit() {
    this.filterData = {
      selectedMonth: 'T042025',
      selectedStore: '',
      selectedPerson: '',
    };
    this.data = this.initData[0].data.lstInputStore;
  }

  onFilterChanged(filterData: any) {
    console.log('Dữ liệu lọc:', filterData);
    this.filterData = filterData;
    this.applyFilter();
  }
  isOpen = false;

  openFilterModal() {
    this.isOpen = true;
  }

  closeFilterModal() {
    this.isOpen = false;
  }
  applyFilter() {
    if (
      this.filterData.selectedStore === '' &&
      this.filterData.selectedPerson === ''
    ) {
      this.data = this.initData[0].data.lstInputStore;
    } else {
      this.data = this.initData[0].data.lstInputStore.filter((item: any) => {
        const storeMatches =
          this.filterData.selectedStore === '' ||
          item.storeId.includes(this.filterData.selectedStore);
        const personMatches =
          this.filterData.selectedPerson === '' ||
          item.lstChamDiem.includes(this.filterData.selectedPerson);
        return storeMatches && personMatches;
      });
    }
  }

  navigateTo(item: any) {
    console.log(item);

    this.router.navigate([`/survey/store/check-list/${item}`]);
  }
  resetFilters() {
    this.filterForm.reset({
      selectedMonth: 'T042025',
      selectedStore: '',
      selectedPerson: '',
      storeChecked: false,
      storeUnchecked: false,
    });
  }

  mockAccounts: any[] = [
    {
      userName: 'kienht',
      fullName: 'Hoàng Trung Kiên',
      phoneNumber: '012345678',
      email: 'Thind@gmail.com',
      address: 'Thanh hóa',
      accountType: null,
      organizeCode: null,
      urlImage: null,
      accountGroups: [],
      accountRights: [],
      isActive: true,
    },
    {
      userName: 'thind',
      fullName: 'Nguyễn Đình Thi',
      phoneNumber: '012345678',
      email: 'Thind@gmail.om',
      address: 'Hưng yên',
      accountType: null,
      organizeCode: null,
      urlImage: null,
      accountGroups: [],
      accountRights: [],
      isActive: true,
    },
    {
      userName: 'phuongtt',
      fullName: 'Trần Thanh Phương',
      phoneNumber: '012345678',
      email: 'phuongtt@gmail.om',
      address: 'Hà Nam',
      accountType: null,
      organizeCode: null,
      urlImage: null,
      accountGroups: [],
      accountRights: [],
      isActive: true,
    },
  ]
  mockStores: any[] = [
    {
      id: '281001',
      phoneNumber: '0383596052',
      name: 'PETROLIMEX-CỬA HÀNG 01',
      cuaHangTruong: 'thind',
      nguoiPhuTrach: 'thind',
      viDo: '2',
      kinhDo: '1',
      trangThaiCuaHang: true,
      storeId: '281001',
      surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
      lstChamDiem: [],
      lstInChamDiem: [],
    },
    {
      id: '281002',
      phoneNumber: '0383852398',
      name: 'PETROLIMEX-CỬA HÀNG 03',
      cuaHangTruong: 'Doãn Thành Vinh',
      nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
      viDo: null,
      kinhDo: null,
      trangThaiCuaHang: true,
      storeId: '281002',
      surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
      lstChamDiem: [],
      lstInChamDiem: [],
    },
    {
      id: '281003',
      phoneNumber: '0383842076',
      name: 'PETROLIMEX-CỬA HÀNG 02',
      cuaHangTruong: 'Nguyễn Thị Vinh',
      nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
      viDo: null,
      kinhDo: null,
      trangThaiCuaHang: true,
      storeId: '281003',
      surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
      lstChamDiem: [],
      lstInChamDiem: [],
    },
    {
      id: '281004',
      phoneNumber: '0383851301',
      name: 'PETROLIMEX-CỬA HÀNG 05',
      cuaHangTruong: 'Võ Duy Giảng',
      nguoiPhuTrach: 'Nguyễn Thị Việt Hà',
      viDo: null,
      kinhDo: null,
      trangThaiCuaHang: true,
      storeId: '281004',
      surveyMgmtId: '03805572-e6b7-4455-90fe-9b6584eef46f',
      lstChamDiem: [],
      lstInChamDiem: [],
    },
  ]

  public actionSheetButtons = [
    {
      text: 'Delete',
      role: 'destructive',
      data: {
        action: 'delete',
      },
    },
    {
      text: 'Share',
      data: {
        action: 'share',
      },
    },
    {
      text: 'Cancel',
      role: 'cancel',
      data: {
        action: 'cancel',
      },
    },
  ];


}
